// POST CONSTANTS
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST ";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS ";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL ";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST ";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS ";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL ";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST ";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS ";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL ";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST ";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS ";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL ";

//USER CONSTANTS

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST ";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS ";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL ";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST ";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS ";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL ";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST ";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS ";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL ";

export const GET_USER_REQUEST = "GET_USER_REQUEST ";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS ";
export const GET_USER_FAIL = "GET_USER_FAIL ";

//LOGIN

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST ";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS ";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL ";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST ";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS ";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL ";

export const ERROR = "ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS ";

export const STOP_LOADING = "STOP_LOADING";

export const CHECK_TOKEN = "CHECK_TOKEN";

export const AVATAR_FETCH = "AVATAR_FETCH";
